[platformio]
boards_dir = .

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200

[env:esp32-poe]
board = esp32-poe

[env:esp32-poe-16mb]
board = esp32-poe-16mb

[env:esp32-poe-wrover]
board = esp32-poe-wrover

[env:esp32-poe-iso]
board = esp32-poe-iso

[env:esp32-poe-iso-16mb]
board = esp32-poe-iso-16mb

[env:esp32-poe-iso-wrover]
board = esp32-poe-iso-wrover
